(
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE',
        PRODUCT_ID,
        USER_ID,
        SUM(SALES_AMOUNT) AS 'SALES_AMOUNT'
    FROM ONLINE_SALE
    WHERE
        YEAR(SALES_DATE) = 2022
        AND MONTH(SALES_DATE) = 3
    GROUP BY PRODUCT_ID, USER_ID, DAY(SALES_DATE)
UNION
    SELECT
        DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS 'SALES_DATE',
        PRODUCT_ID,
        NULL AS 'USER_ID',
        SUM(SALES_AMOUNT) AS 'SALES_AMOUNT'
    FROM OFFLINE_SALE
    WHERE
        YEAR(SALES_DATE) = 2022
        AND MONTH(SALES_DATE) = 3
    GROUP BY PRODUCT_ID, USER_ID, DAY(SALES_DATE)
)
ORDER BY
    SALES_DATE ASC,
    PRODUCT_ID ASC,
    USER_ID ASC
;