SELECT UGU.USER_ID,
    UGU.NICKNAME,
    CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS 전체주소,
    CONCAT(LEFT(UGU.TLNO, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', RIGHT(UGU.TLNO, 4)) AS 전화번호
FROM USED_GOODS_BOARD AS UGB
    JOIN USED_GOODS_USER AS UGU
    ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(BOARD_ID) > 2
ORDER BY UGU.USER_ID DESC;