WITH USER_2021 AS (
    SELECT
        USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
ONLINE_SALE_USER_2021 AS (
    SELECT
        YEAR(A.SALES_DATE) AS YEAR,
        MONTH(A.SALES_DATE) AS MONTH,
        COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE A
    JOIN USER_2021 B
    ON A.USER_ID = B.USER_ID
    GROUP BY YEAR, MONTH
)

SELECT
    YEAR,
    MONTH,
    PURCHASED_USERS,
    ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM USER_2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE_USER_2021
ORDER BY YEAR ASC, MONTH ASC;