WITH TRUCK_CARS AS (
    SELECT
        CAR_ID,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
TRUCK_DISCOUNT AS (
    SELECT
        CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS DISCOUNT_MIN_DAY,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
TRUCK_RENTALS AS (
    SELECT
        A.HISTORY_ID,
        A.CAR_ID,
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS RENTAL_DAY,
        B.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN TRUCK_CARS B
    ON A.CAR_ID = B.CAR_ID
)

SELECT
    A.HISTORY_ID,
    TRUNCATE((A.RENTAL_DAY * A.DAILY_FEE) * (100 - IFNULL(B.DISCOUNT_RATE, 0)) * 0.01, 0) AS FEE
FROM TRUCK_RENTALS A
LEFT JOIN TRUCK_DISCOUNT B
ON B.DISCOUNT_MIN_DAY = (
    SELECT
        MAX(C.DISCOUNT_MIN_DAY)
    FROM TRUCK_DISCOUNT C
    WHERE C.DISCOUNT_MIN_DAY <= A.RENTAL_DAY
)
ORDER BY FEE DESC, HISTORY_ID DESC