WITH TRUCK_CARS AS (
    SELECT
        CAR_ID,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
TRUCK_DISCOUNT AS (
    SELECT
        CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS DISCOUNT_MIN_DAY,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
TRUCK_RENTALS AS (
    SELECT
        A.HISTORY_ID,
        A.CAR_ID,
        DATEDIFF(A.END_DATE, A.START_DATE) + 1 AS RENTAL_DAY,
        B.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN TRUCK_CARS B
    ON A.CAR_ID = B.CAR_ID
),
TRUCK_RENTALS_FEE AS (
    SELECT
        A.HISTORY_ID,
        A.RENTAL_DAY * A.DAILY_FEE AS FEE,
        B.DISCOUNT_RATE,
        RANK() OVER (PARTITION BY A.HISTORY_ID ORDER BY B.DISCOUNT_MIN_DAY DESC) AS DISCOUNT_RATE_RANK
    FROM TRUCK_RENTALS A
    LEFT JOIN TRUCK_DISCOUNT B
    ON B.DISCOUNT_MIN_DAY <= A.RENTAL_DAY
)

SELECT
    HISTORY_ID,
    TRUNCATE(FEE * (1 - IFNULL(DISCOUNT_RATE, 0) / 100), 0) AS FEE
FROM TRUCK_RENTALS_FEE
WHERE DISCOUNT_RATE_RANK = 1
ORDER BY FEE DESC, HISTORY_ID DESC;