WITH ORDER_SUM AS (
    SELECT
        FLAVOR,
        SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM
        ((SELECT
            FLAVOR,
            SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR)
        UNION
        (SELECT
            FLAVOR,
            SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR)) AS A
    GROUP BY FLAVOR
)
SELECT
    FLAVOR
FROM ORDER_SUM
ORDER BY TOTAL_ORDER DESC
LIMIT 3;