SELECT DISTINCT(CCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CCC
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CCRH
    ON CCC.CAR_ID = CCRH.CAR_ID
WHERE CCC.CAR_TYPE = '세단'
    AND MONTH(CCRH.START_DATE) = 10
ORDER BY CCC.CAR_ID DESC;