WITH MAX_LENGTH_FISH AS (
    SELECT
        FISH_TYPE,
        MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT
    A.ID,
    C.FISH_NAME,
    A.LENGTH
FROM FISH_INFO A
JOIN MAX_LENGTH_FISH B
ON A.FISH_TYPE = B.FISH_TYPE
    AND A.LENGTH = B.LENGTH
JOIN FISH_NAME_INFO C
ON A.FISH_TYPE = C.FISH_TYPE;