WITH LONG_FISH AS (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH,
        RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS LENGTH_RANK
    FROM FISH_INFO
)
SELECT
    A.ID,
    B.FISH_NAME,
    A.LENGTH
FROM LONG_FISH AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE LENGTH_RANK = 1
ORDER BY ID ASC;