SELECT HGR.SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL
FROM HR_EMPLOYEES AS HE
    JOIN (SELECT EMP_NO,
            SUM(SCORE) AS SCORE,
            RANK() OVER (ORDER BY SUM(SCORE) DESC) AS RANKING
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO) AS HGR
    ON HE.EMP_NO = HGR.EMP_NO
WHERE RANKING = 1